apiVersion: v1
kind: ConfigMap
metadata:
  name: curator-config
  namespace: elk
data:
  action_file.yml: |-
    actions:
      1:
        action: delete_indices
        description: >-
          Delete indices older than 2 days (based on index name), for logstash-
          prefixed indices. Ignore the error if the filter does not result in an
          actionable list of indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
          disable_action: False
          continue_if_exception: True
        filters:
        - filtertype: pattern
          kind: prefix
          value: logstash-
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 2
      2:
        action: delete_indices
        description: >-
          Delete indices older than 2 days (based on index name), for apm-
          prefixed indices. Ignore the error if the filter does not result in an
          actionable list of indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
          disable_action: False
          continue_if_exception: True
        filters:
        - filtertype: pattern
          kind: prefix
          value: apm-
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 2
      3:
        action: delete_indices
        description: >-
          Delete indices older than 2 days (based on index name), for apm-
          prefixed indices. Ignore the error if the filter does not result in an
          actionable list of indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
          disable_action: False
          continue_if_exception: True
        filters:
        - filtertype: pattern
          kind: prefix
          value: fluentd-
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 3
  config.yml: |-
    ---
    # Remember, leave a key empty if there is no value.  None will be a string,
    # not a Python "NoneType"
    client:
      hosts:
        - elasticsearch
      port: 9200
      url_prefix:
      use_ssl: False
      certificate:
      client_cert:
      client_key:
      ssl_no_validate: False
      http_auth: ${ELASTIC_CREDS}
      timeout: 30
      master_only: False

    logging:
      loglevel: INFO
      logfile:
      logformat: default
      blacklist: ['elasticsearch', 'urllib3']

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: curator
  namespace: elk
spec:
  schedule: 00 12 * * *
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curator
            image: bobrik/curator
            args: ["--config", "/etc/config/config.yml", "/etc/config/action_file.yml"]
            volumeMounts:
              - name: config-volume
                mountPath: /etc/config
            env:
              - name: ELASTIC_USER
                value: elastic
              - name: ELASTIC_PASS
                valueFrom:
                  secretKeyRef:
                    name: bff-elk-pw-prd-elastic
                    key: password
              - name: ELASTIC_CREDS
                value: $(ELASTIC_USER):$(ELASTIC_PASS)
          volumes:
            - name: config-volume
              configMap:
                name: curator-config
          restartPolicy: OnFailure

                  