variable "project" {}
variable "region" {}
variable "vpc_cidr_dev" {}
variable "vpc_cidr_hml" {}
variable "vpc_cidr_prd" {}
variable "vpc_name" {}
variable "sub_priv_dev_name" {}
variable "sub_priv_hml_name" {}
variable "sub_priv_prd_name" {}
variable "initial_node_count_dev" {}
variable "nat_name" {}
variable "router_name" {}
variable "cluster_secondary_range_name_dev" {}
variable "services_secondary_range_name_dev" {}
variable "cluster_secondary_range_name_hml" {}
variable "services_secondary_range_name_hml" {}
variable "cluster_secondary_range_name_prd" {}
variable "services_secondary_range_name_prd" {}
variable "pods_cidr_dev" {}
variable "pods_cidr_hml" {}
variable "pods_cidr_prd" {}
variable "services_cidr_dev" {}
variable "services_cidr_hml" {}
variable "services_cidr_prd" {}
variable "bastion_subnet" {}
variable "cidr_bastion_subnet" {}
variable "nat_ips" {}
